### ISSUE TITLE
Invalid orderId

### ISSUE THREAD

**Issue by hackerz12on** [dmmdust/Commercial-Bank-Payment-Gateway-WooCommerce#1]
In case the payment failed and returned back to the checkout page, the page seems to have the same order id.
How can we change this ??

**Comment by dhanmalage** [comment]
This repository is very old and not updating. Woocommerce and bank payment gateway must have changed a lot since. 
Woocommerce create the order when you fill out checkout form and order status is pending. after returning back to website you have to change order ID based on payment status. Most payment gateways let you send additional data to payment gateway and get them returned. you can catch order ID from there if it's possible.
